export const GET_COUNTRY_BY_PRODUCT = 'GET_COUNTRY_BY_PRODUCT';
export const GET_PRODUCT_BY_COUNTRY = 'GET_PRODUCT_BY_COUNTRY';
export const LOG_IN = 'LOG_IN';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
// export const ADD_PRODUCT_TO_COUNTRY = 'ADD_PRODUCT_TO_COUNTRY';
// export const DELETE_PRODUCT_FROM_COUNTRY = 'DELETE_PRODUCT_FROM_COUNTRY';