export const GET_COUNTRY_BY_PRODUCT = 'GET_COUNTRY_BY_PRODUCT';
export const GET_PRODUCT_BY_COUNTRY = 'GET_PRODUCT_BY_COUNTRY';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_COUNTRY = 'GET_COUNTRY';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INVALID = 'INVALID';